/**
 * SPWN Apps 2.0 - Role-Based Access Control & Permission System
 * Location: src/types/permissions.ts
 */

export const PERMISSIONS = {
  // Member domain
  MEMBER_READ: 'MEMBER_READ',
  MEMBER_CREATE: 'MEMBER_CREATE',
  MEMBER_UPDATE: 'MEMBER_UPDATE',
  MEMBER_DEACTIVATE: 'MEMBER_DEACTIVATE',
  MEMBER_REGISTER: 'MEMBER_REGISTER',
  MEMBER_REVIEW: 'MEMBER_REVIEW',
  MEMBER_APPROVE: 'MEMBER_APPROVE',
  MEMBER_EDIT: 'MEMBER_EDIT',
  MEMBER_RESET_PASSWORD: 'MEMBER_RESET_PASSWORD',

  // KTA & QR Identity domain
  KTA_GENERATE: 'KTA_GENERATE',
  KTA_TEMPLATE_MANAGE: 'KTA_TEMPLATE_MANAGE',
  QR_REGENERATE: 'QR_REGENERATE',
  
  // Verification domain
  VERIFY_KTA_PUBLIC: 'VERIFY_KTA_PUBLIC',
  VERIFY_KTA_INTERNAL: 'VERIFY_KTA_INTERNAL',
  
  // Tourism domain
  TOURISM_READ: 'TOURISM_READ',
  TOURISM_MANAGE: 'TOURISM_MANAGE',
  TOURISM_REVIEW: 'TOURISM_REVIEW',
  
  // Content domain
  CONTENT_READ: 'CONTENT_READ',
  CONTENT_CREATE: 'CONTENT_CREATE',
  CONTENT_REVIEW: 'CONTENT_REVIEW',
  CONTENT_PUBLISH: 'CONTENT_PUBLISH',
  
  // Commerce domain
  COMMERCE_READ: 'COMMERCE_READ',
  COMMERCE_BUY: 'COMMERCE_BUY',
  COMMERCE_MANAGE: 'COMMERCE_MANAGE',
  
  // Admin & System domain
  SYSTEM_AUDIT_READ: 'SYSTEM_AUDIT_READ',
  SYSTEM_CONFIG_MANAGE: 'SYSTEM_CONFIG_MANAGE',
} as const;

export type PermissionKey = (typeof PERMISSIONS)[keyof typeof PERMISSIONS];

/**
 * Pemetaan default izin hak akses berdasarkan Peran Akun Pengguna
 */
export const ROLE_DEFAULT_PERMISSIONS: Record<string, PermissionKey[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN_PUSAT: [
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_CREATE,
    PERMISSIONS.MEMBER_UPDATE,
    PERMISSIONS.MEMBER_DEACTIVATE,
    PERMISSIONS.MEMBER_APPROVE,
    PERMISSIONS.MEMBER_EDIT,
    PERMISSIONS.MEMBER_RESET_PASSWORD,
    PERMISSIONS.KTA_GENERATE,
    PERMISSIONS.QR_REGENERATE,
    PERMISSIONS.VERIFY_KTA_PUBLIC,
    PERMISSIONS.VERIFY_KTA_INTERNAL,
    PERMISSIONS.TOURISM_READ,
    PERMISSIONS.TOURISM_MANAGE,
    PERMISSIONS.TOURISM_REVIEW,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_REVIEW,
    PERMISSIONS.CONTENT_PUBLISH,
    PERMISSIONS.COMMERCE_READ,
    PERMISSIONS.COMMERCE_BUY,
    PERMISSIONS.COMMERCE_MANAGE,
    PERMISSIONS.SYSTEM_AUDIT_READ,
  ],
  ADMIN_WILAYAH: [
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.MEMBER_REVIEW,
    PERMISSIONS.MEMBER_EDIT,
    PERMISSIONS.VERIFY_KTA_PUBLIC,
    PERMISSIONS.VERIFY_KTA_INTERNAL,
    PERMISSIONS.TOURISM_READ,
    PERMISSIONS.TOURISM_MANAGE,
    PERMISSIONS.TOURISM_REVIEW,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_REVIEW,
    PERMISSIONS.COMMERCE_READ,
    PERMISSIONS.COMMERCE_BUY,
    PERMISSIONS.COMMERCE_MANAGE,
    PERMISSIONS.SYSTEM_AUDIT_READ,
  ],
  CONTENT_MANAGER: [
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.CONTENT_CREATE,
    PERMISSIONS.CONTENT_REVIEW,
    PERMISSIONS.CONTENT_PUBLISH,
    PERMISSIONS.TOURISM_READ,
    PERMISSIONS.VERIFY_KTA_PUBLIC,
    PERMISSIONS.MEMBER_READ,
  ],
  TOURISM_MANAGER: [
    PERMISSIONS.TOURISM_READ,
    PERMISSIONS.TOURISM_MANAGE,
    PERMISSIONS.TOURISM_REVIEW,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.VERIFY_KTA_PUBLIC,
  ],
  COMMERCE_MANAGER: [
    PERMISSIONS.COMMERCE_READ,
    PERMISSIONS.COMMERCE_MANAGE,
    PERMISSIONS.COMMERCE_BUY,
    PERMISSIONS.MEMBER_READ,
  ],
  MEMBER: [
    PERMISSIONS.MEMBER_READ,
    PERMISSIONS.VERIFY_KTA_PUBLIC,
    PERMISSIONS.TOURISM_READ,
    PERMISSIONS.TOURISM_REVIEW,
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.CONTENT_CREATE, // Draft warta
    PERMISSIONS.COMMERCE_READ,
    PERMISSIONS.COMMERCE_BUY,
  ],
  PUBLIC_USER: [
    PERMISSIONS.MEMBER_REGISTER,
    PERMISSIONS.VERIFY_KTA_PUBLIC,
    PERMISSIONS.TOURISM_READ,
    PERMISSIONS.TOURISM_REVIEW, // Dual gate with rate limit
    PERMISSIONS.CONTENT_READ,
    PERMISSIONS.COMMERCE_READ,
  ]
};
